export interface VPartesDatoInterface {
  AñoNum: number;
  Bloqueado: boolean;
  Cantidad: number;
  Causa: string | null;
  Cierre_CentroCoste: string | null;
  Cierre_Desglose: string | null;
  Cierre_SubCuenta: string | null;
  Cierre_Tipo: string | null;
  ContadorDesde: number;
  ContadorHasta: number;
  Descrip: string;
  Descuento: number;
  DesplDetall: boolean;
  DireccionReparacion: string | null;
  Documentacion: boolean;
  EnGarantia: boolean;
  EntregaAccesorios: boolean;
  Facturable: boolean;
  FacturarGarantiaA: string | null;
  FechaAceptacionPresupuesto: string | null;
  FechaEntrada: string;
  FechaFin: string | null;
  FechaFinEstimada: string | null;
  FechaInicio: string | null;
  FechaInsertUpdate: string;
  FechaParte: string;
  FechaPresupuesto: string | null;
  FechaSalida: string;
  FormaPago: number;
  Garantia: number;
  HoraAviso: string | null;
  HoraFin: string;
  HoraInicio: string | null;
  IdAlmacenOrigen: number;
  IdAnomalia: number;
  IdArticulo: string;
  IdAveria: number;
  IdCaja: number | null;
  IdCentroCoste: number | null;
  IdClasificacion: number;
  IdCliente: string;
  IdClienteAlt: string | null;
  IdContacto: number;
  IdDoc: number;
  IdEmpleado: number;
  IdEmpleadoBloqueo: number | null;
  IdEquipo: number | null;
  IdEstado: number;
  IdEstadoReparacion: number;
  IdLista: number;
  IdMarcaMaquina: number;
  IdMoneda: number;
  IdMotivoBloqueo: number | null;
  IdOferta: number | null;
  IdParte: number;
  IdPedido: number | null;
  IdPedidoGarantia: number | null;
  IdProveedor: number | null;
  IdProyecto: number | null;
  IdRevisionTipo: number | null;
  IdServicioGrua: number | null;
  IdSubtipo: number;
  IdTaller: number;
  IdTipoMaquina: number;
  IdTipoParte: number;
  InsertUpdate: boolean;
  Iva: number;
  ManoObraDetall: boolean;
  ModeloMaquina: string | null;
  NumParte: number;
  NumSerie: string | null;
  Observaciones: string | null;
  OrigenGarantia: number;
  PersonaContacto: string | null;
  Presupuesto: boolean;
  Prioridad: number;
  QuienEntregaMaq: number;
  ReparacionEnCli: boolean;
  ReparandoEnExterior: boolean;
  Revision: string | null;
  SerieFacturacion: number;
  Telefono: string | null;
  UnidadesGarantia: number;
  Usuario: string;
}

